//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyChat.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyChat.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A translator chatbot that can translate your messages to different languages..
        /// </summary>
        public static string AboutLine1 {
            get {
                return ResourceManager.GetString("AboutLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a refactored version of the original EasyChat project..
        /// </summary>
        public static string AboutLine2 {
            get {
                return ResourceManager.GetString("AboutLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color.
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing Translate.
        /// </summary>
        public static string Action_InputTranslate {
            get {
                return ResourceManager.GetString("Action_InputTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Translate.
        /// </summary>
        public static string Action_ScreenshotTranslate {
            get {
                return ResourceManager.GetString("Action_ScreenshotTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Engine, Source &amp; Target.
        /// </summary>
        public static string Action_SwitchEngineSourceTarget {
            get {
                return ResourceManager.GetString("Action_SwitchEngineSourceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Source Language.
        /// </summary>
        public static string Action_SwitchSourceLang {
            get {
                return ResourceManager.GetString("Action_SwitchSourceLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Target Language.
        /// </summary>
        public static string Action_SwitchTargetLang {
            get {
                return ResourceManager.GetString("Action_SwitchTargetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type.
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Basic Shortcut.
        /// </summary>
        public static string AddBasicShortcut {
            get {
                return ResourceManager.GetString("AddBasicShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Key.
        /// </summary>
        public static string AddKey {
            get {
                return ResourceManager.GetString("AddKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Language Shortcut.
        /// </summary>
        public static string AddLanguageShortcut {
            get {
                return ResourceManager.GetString("AddLanguageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Model.
        /// </summary>
        public static string AddModel {
            get {
                return ResourceManager.GetString("AddModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Prompt.
        /// </summary>
        public static string AddPrompt {
            get {
                return ResourceManager.GetString("AddPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Model.
        /// </summary>
        public static string AIEngine {
            get {
                return ResourceManager.GetString("AIEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply To.
        /// </summary>
        public static string ApplyTo {
            get {
                return ResourceManager.GetString("ApplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyChat.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this shortcut?.
        /// </summary>
        public static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baidu.
        /// </summary>
        public static string Baidu {
            get {
                return ResourceManager.GetString("Baidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Shortcuts.
        /// </summary>
        public static string BasicShortcuts {
            get {
                return ResourceManager.GetString("BasicShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the default prompt. Please set another prompt as default first..
        /// </summary>
        public static string CannotDeleteDefaultPrompt {
            get {
                return ResourceManager.GetString("CannotDeleteDefaultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the last prompt..
        /// </summary>
        public static string CannotDeleteLastPrompt {
            get {
                return ResourceManager.GetString("CannotDeleteLastPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your network connection..
        /// </summary>
        public static string CheckNetwork {
            get {
                return ResourceManager.GetString("CheckNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claude.
        /// </summary>
        public static string Claude {
            get {
                return ResourceManager.GetString("Claude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Record.
        /// </summary>
        public static string ClickToRecord {
            get {
                return ResourceManager.GetString("ClickToRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to Tray.
        /// </summary>
        public static string CloseToTray {
            get {
                return ResourceManager.GetString("CloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to minimize to tray or exit the application?.
        /// </summary>
        public static string CloseToTrayPromptMessage {
            get {
                return ResourceManager.GetString("CloseToTrayPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Action.
        /// </summary>
        public static string CloseToTrayPromptTitle {
            get {
                return ResourceManager.GetString("CloseToTrayPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Action.
        /// </summary>
        public static string ClosingBehavior {
            get {
                return ResourceManager.GetString("ClosingBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color has changed to.
        /// </summary>
        public static string ColorChangedContent {
            get {
                return ResourceManager.GetString("ColorChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Changed.
        /// </summary>
        public static string ColorChangedTitle {
            get {
                return ResourceManager.GetString("ColorChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this model?.
        /// </summary>
        public static string ConfirmDeleteModel {
            get {
                return ResourceManager.GetString("ConfirmDeleteModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this prompt?.
        /// </summary>
        public static string ConfirmDeletePrompt {
            get {
                return ResourceManager.GetString("ConfirmDeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful!.
        /// </summary>
        public static string ConnectionSuccess {
            get {
                return ResourceManager.GetString("ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Bilingual.
        /// </summary>
        public static string CopyBilingual {
            get {
                return ResourceManager.GetString("CopyBilingual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Original.
        /// </summary>
        public static string CopyOriginal {
            get {
                return ResourceManager.GetString("CopyOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©️ EasyChatOrg.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Translated.
        /// </summary>
        public static string CopyTranslated {
            get {
                return ResourceManager.GetString("CopyTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Custom.
        /// </summary>
        public static string CreateCustom {
            get {
                return ResourceManager.GetString("CreateCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Model.
        /// </summary>
        public static string CustomModel {
            get {
                return ResourceManager.GetString("CustomModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepL.
        /// </summary>
        public static string DeepL {
            get {
                return ResourceManager.GetString("DeepL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultPrompt {
            get {
                return ResourceManager.GetString("DefaultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Model.
        /// </summary>
        public static string DeleteModel {
            get {
                return ResourceManager.GetString("DeleteModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message (Compatibility).
        /// </summary>
        public static string DeliveryMode_Message {
            get {
                return ResourceManager.GetString("DeliveryMode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Clipboard).
        /// </summary>
        public static string DeliveryMode_Paste {
            get {
                return ResourceManager.GetString("DeliveryMode_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing (Simulate).
        /// </summary>
        public static string DeliveryMode_Type {
            get {
                return ResourceManager.GetString("DeliveryMode_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Keys.
        /// </summary>
        public static string EditKeys {
            get {
                return ResourceManager.GetString("EditKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Model.
        /// </summary>
        public static string EditModel {
            get {
                return ResourceManager.GetString("EditModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Prompt.
        /// </summary>
        public static string EditPrompt {
            get {
                return ResourceManager.GetString("EditPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Calculate Delay.
        /// </summary>
        public static string EnableAutoReadDelay {
            get {
                return ResourceManager.GetString("EnableAutoReadDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable System Tray.
        /// </summary>
        public static string EnableTray {
            get {
                return ResourceManager.GetString("EnableTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Window.
        /// </summary>
        public static string FloatingWindow {
            get {
                return ResourceManager.GetString("FloatingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        public static string FloatingWindow_Close {
            get {
                return ResourceManager.GetString("FloatingWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Window Configuration.
        /// </summary>
        public static string FloatingWindow_Config {
            get {
                return ResourceManager.GetString("FloatingWindow_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Window.
        /// </summary>
        public static string FloatingWindow_Lock {
            get {
                return ResourceManager.GetString("FloatingWindow_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Window.
        /// </summary>
        public static string FloatingWindow_Open {
            get {
                return ResourceManager.GetString("FloatingWindow_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Window (Click-Through).
        /// </summary>
        public static string FloatingWindow_Unlock {
            get {
                return ResourceManager.GetString("FloatingWindow_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the app fullscreen..
        /// </summary>
        public static string FullScreenTip {
            get {
                return ResourceManager.GetString("FullScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini.
        /// </summary>
        public static string Gemini {
            get {
                return ResourceManager.GetString("Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider,Source,Target (e.g. Baidu,en,zh).
        /// </summary>
        public static string Hint_SwitchConfig {
            get {
                return ResourceManager.GetString("Hint_SwitchConfig", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Fixed Areas.
        /// </summary>
        public static string FixedAreas {
            get {
                return ResourceManager.GetString("FixedAreas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a region for the fixed area..
        /// </summary>
        public static string FixedArea_Hint {
            get {
                return ResourceManager.GetString("FixedArea_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No fixed areas.
        /// </summary>
        public static string NoFixedAreas {
            get {
                return ResourceManager.GetString("NoFixedAreas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Fixed Area.
        /// </summary>
        public static string AddFixedArea {
            get {
                return ResourceManager.GetString("AddFixedArea", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Translate.
        /// </summary>
        public static string ImageTranslate {
            get {
                return ResourceManager.GetString("ImageTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Delivery Mode.
        /// </summary>
        public static string InputDeliveryMode {
            get {
                return ResourceManager.GetString("InputDeliveryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Window.
        /// </summary>
        public static string InputSettings {
            get {
                return ResourceManager.GetString("InputSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input text to translate....
        /// </summary>
        public static string InputToTranslate {
            get {
                return ResourceManager.GetString("InputToTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Combination.
        /// </summary>
        public static string KeyCombination {
            get {
                return ResourceManager.GetString("KeyCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Send Delay.
        /// </summary>
        public static string KeySendDelay {
            get {
                return ResourceManager.GetString("KeySendDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed.
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Switch Shortcuts.
        /// </summary>
        public static string LanguageShortcuts {
            get {
                return ResourceManager.GetString("LanguageShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Trans.
        /// </summary>
        public static string MachineTranslation {
            get {
                return ResourceManager.GetString("MachineTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray.
        /// </summary>
        public static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type.
        /// </summary>
        public static string ModelType {
            get {
                return ResourceManager.GetString("ModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms/Char.
        /// </summary>
        public static string MsPerChar {
            get {
                return ResourceManager.GetString("MsPerChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version {0} is available!.
        /// </summary>
        public static string NewVersionContent {
            get {
                return ResourceManager.GetString("NewVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        public static string OcrKey {
            get {
                return ResourceManager.GetString("OcrKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI.
        /// </summary>
        public static string OpenAI {
            get {
                return ResourceManager.GetString("OpenAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on Github..
        /// </summary>
        public static string OpenOnGithub {
            get {
                return ResourceManager.GetString("OpenOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on official site..
        /// </summary>
        public static string OpenOnOfficialSite {
            get {
                return ResourceManager.GetString("OpenOnOfficialSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Every Time.
        /// </summary>
        public static string Option_Ask {
            get {
                return ResourceManager.GetString("Option_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string Option_Exit {
            get {
                return ResourceManager.GetString("Option_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray.
        /// </summary>
        public static string Option_Minimize {
            get {
                return ResourceManager.GetString("Option_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition.
        /// </summary>
        public static string Page_SpeechRecognition {
            get {
                return ResourceManager.GetString("Page_SpeechRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter (e.g. zh, en).
        /// </summary>
        public static string ParameterHint {
            get {
                return ResourceManager.GetString("ParameterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Color.
        /// </summary>
        public static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string PromptContent {
            get {
                return ResourceManager.GetString("PromptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PromptName {
            get {
                return ResourceManager.GetString("PromptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported parameters: [SourceLang], [TargetLang], [源语言], [目标语言].
        /// </summary>
        public static string PromptParametersHint {
            get {
                return ResourceManager.GetString("PromptParametersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompts.
        /// </summary>
        public static string Prompts {
            get {
                return ResourceManager.GetString("Prompts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://username:password@server:port.
        /// </summary>
        public static string ProxyAddrQuestion {
            get {
                return ResourceManager.GetString("ProxyAddrQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Type.
        /// </summary>
        public static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using for TranslationAPI requests. Like OpenAI, Gemini etc..
        /// </summary>
        public static string ProxyTypeQuestion {
            get {
                return ResourceManager.GetString("ProxyTypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Url.
        /// </summary>
        public static string ProxyUrl {
            get {
                return ResourceManager.GetString("ProxyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key combination....
        /// </summary>
        public static string RecordingShortcut {
            get {
                return ResourceManager.GetString("RecordingShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Shortcut.
        /// </summary>
        public static string RecordShortcut {
            get {
                return ResourceManager.GetString("RecordShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my choice.
        /// </summary>
        public static string RememberMyChoice {
            get {
                return ResourceManager.GetString("RememberMyChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request error, maybe internet connection issues..
        /// </summary>
        public static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application to take effect..
        /// </summary>
        public static string RestartToTakeEffect {
            get {
                return ResourceManager.GetString("RestartToTakeEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored!.
        /// </summary>
        public static string RestoreSuccess {
            get {
                return ResourceManager.GetString("RestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Close Delay.
        /// </summary>
        public static string ResultAutoCloseDelay {
            get {
                return ResourceManager.GetString("ResultAutoCloseDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Window.
        /// </summary>
        public static string ResultSettings {
            get {
                return ResourceManager.GetString("ResultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the area to translate. Right-click or ESC to cancel..
        /// </summary>
        public static string Screenshot_Hint {
            get {
                return ResourceManager.GetString("Screenshot_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Mode.
        /// </summary>
        public static string ScreenshotMode {
            get {
                return ResourceManager.GetString("ScreenshotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precise (Toolbar).
        /// </summary>
        public static string ScreenshotMode_Precise {
            get {
                return ResourceManager.GetString("ScreenshotMode_Precise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick (No Confirm).
        /// </summary>
        public static string ScreenshotMode_Quick {
            get {
                return ResourceManager.GetString("ScreenshotMode_Quick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default.
        /// </summary>
        public static string SetAsDefault {
            get {
                return ResourceManager.GetString("SetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Lang.
        /// </summary>
        public static string SourceLang {
            get {
                return ResourceManager.GetString("SourceLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global (All System Audio).
        /// </summary>
        public static string Speech_AllSystemAudio {
            get {
                return ResourceManager.GetString("Speech_AllSystemAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Source.
        /// </summary>
        public static string Speech_AudioSource {
            get {
                return ResourceManager.GetString("Speech_AudioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string Speech_DisplayMode {
            get {
                return ResourceManager.GetString("Speech_DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scroll.
        /// </summary>
        public static string Speech_DisplayMode_AutoScroll {
            get {
                return ResourceManager.GetString("Speech_DisplayMode_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmented.
        /// </summary>
        public static string Speech_DisplayMode_Segmented {
            get {
                return ResourceManager.GetString("Speech_DisplayMode_Segmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Translation.
        /// </summary>
        public static string Speech_EnableTranslation {
            get {
                return ResourceManager.GetString("Speech_EnableTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Visible Lines.
        /// </summary>
        public static string Speech_MaxHistory {
            get {
                return ResourceManager.GetString("Speech_MaxHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentences Per Line.
        /// </summary>
        public static string Speech_MaxSentencesPerLine {
            get {
                return ResourceManager.GetString("Speech_MaxSentencesPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is only supported on Windows..
        /// </summary>
        public static string Speech_NotSupported {
            get {
                return ResourceManager.GetString("Speech_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time Preview.
        /// </summary>
        public static string Speech_RealTimePreview {
            get {
                return ResourceManager.GetString("Speech_RealTimePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to translate partial results. Disable to translate only confirmed sentences..
        /// </summary>
        public static string Speech_RealTimePreviewTip {
            get {
                return ResourceManager.GetString("Speech_RealTimePreviewTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized.
        /// </summary>
        public static string Speech_Recognized {
            get {
                return ResourceManager.GetString("Speech_Recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Speech_Refresh {
            get {
                return ResourceManager.GetString("Speech_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} apps.
        /// </summary>
        public static string Speech_SelectedAppsCount {
            get {
                return ResourceManager.GetString("Speech_SelectedAppsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Audio Source.
        /// </summary>
        public static string Speech_SelectSourceTitle {
            get {
                return ResourceManager.GetString("Speech_SelectSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recognition.
        /// </summary>
        public static string Speech_Start {
            get {
                return ResourceManager.GetString("Speech_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recognition.
        /// </summary>
        public static string Speech_Stop {
            get {
                return ResourceManager.GetString("Speech_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated.
        /// </summary>
        public static string Speech_Translated {
            get {
                return ResourceManager.GetString("Speech_Translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle BG.
        /// </summary>
        public static string Subtitle_Background {
            get {
                return ResourceManager.GetString("Subtitle_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Subtitle (Main).
        /// </summary>
        public static string Subtitle_Primary {
            get {
                return ResourceManager.GetString("Subtitle_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Subtitle (Aux).
        /// </summary>
        public static string Subtitle_Secondary {
            get {
                return ResourceManager.GetString("Subtitle_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Subtitle_Source_None {
            get {
                return ResourceManager.GetString("Subtitle_Source_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string Subtitle_Source_Original {
            get {
                return ResourceManager.GetString("Subtitle_Source_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated.
        /// </summary>
        public static string Subtitle_Source_Translated {
            get {
                return ResourceManager.GetString("Subtitle_Source_Translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch To....
        /// </summary>
        public static string SwitchTo {
            get {
                return ResourceManager.GetString("SwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition.
        /// </summary>
        public static string Tab_Recognition {
            get {
                return ResourceManager.GetString("Tab_Recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Lang.
        /// </summary>
        public static string TargetLang {
            get {
                return ResourceManager.GetString("TargetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tencent.
        /// </summary>
        public static string Tencent {
            get {
                return ResourceManager.GetString("Tencent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing....
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme has changed to .
        /// </summary>
        public static string ThemeChangedContent {
            get {
                return ResourceManager.GetString("ThemeChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Changed.
        /// </summary>
        public static string ThemeChangedTitle {
            get {
                return ResourceManager.GetString("ThemeChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Name.
        /// </summary>
        public static string ThemeName {
            get {
                return ResourceManager.GetString("ThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Bar.
        /// </summary>
        public static string TitleBar {
            get {
                return ResourceManager.GetString("TitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window title bar has been .
        /// </summary>
        public static string TitleBarContent {
            get {
                return ResourceManager.GetString("TitleBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the title bar..
        /// </summary>
        public static string TitleBarTip {
            get {
                return ResourceManager.GetString("TitleBarTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Bar .
        /// </summary>
        public static string TitleBarTitle {
            get {
                return ResourceManager.GetString("TitleBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To Toggle Top Menu..
        /// </summary>
        public static string ToggleMenuTip {
            get {
                return ResourceManager.GetString("ToggleMenuTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        public static string ToggleMode {
            get {
                return ResourceManager.GetString("ToggleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Engine.
        /// </summary>
        public static string TransEngine {
            get {
                return ResourceManager.GetString("TransEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate to Window.
        /// </summary>
        public static string TranslateToWindow {
            get {
                return ResourceManager.GetString("TranslateToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency Level.
        /// </summary>
        public static string TransparencyLevel {
            get {
                return ResourceManager.GetString("TransparencyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string TrayShow {
            get {
                return ResourceManager.GetString("TrayShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something here.
        /// </summary>
        public static string TypeSomethingHere {
            get {
                return ResourceManager.GetString("TypeSomethingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing to translate.
        /// </summary>
        public static string TypingViewTitle {
            get {
                return ResourceManager.GetString("TypingViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy.
        /// </summary>
        public static string UseProxy {
            get {
                return ResourceManager.GetString("UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string UsingAiModel {
            get {
                return ResourceManager.GetString("UsingAiModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MachineTrans.
        /// </summary>
        public static string UsingMachineTransEngine {
            get {
                return ResourceManager.GetString("UsingMachineTransEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Release.
        /// </summary>
        public static string ViewRelease {
            get {
                return ResourceManager.GetString("ViewRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Appearance.
        /// </summary>
        public static string Window_Appearance {
            get {
                return ResourceManager.GetString("Window_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window BG.
        /// </summary>
        public static string Window_Background {
            get {
                return ResourceManager.GetString("Window_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string Window_Opacity {
            get {
                return ResourceManager.GetString("Window_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string Window_Orientation {
            get {
                return ResourceManager.GetString("Window_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Background.
        /// </summary>
        public static string WindowBackgroundColor {
            get {
                return ResourceManager.GetString("WindowBackgroundColor", resourceCulture);
            }
        }
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }

        public static string ReselectArea {
            get {
                return ResourceManager.GetString("ReselectArea", resourceCulture);
            }
        }

        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }

        public static string FixedAreaSettings {
            get {
                return ResourceManager.GetString("FixedAreaSettings", resourceCulture);
            }
        }
    }
}
