<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\EasyChat.Contracts\EasyChat.Contracts.csproj" />
    <ProjectReference Include="..\..\EasyChat.Shared\EasyChat.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GlobalHotKeys.Windows" Version="0.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.11.0.20250507" />
    <PackageReference Include="Sdcb.OpenVINO.PaddleOCR" Version="0.8.1" />
    <PackageReference Include="Sdcb.OpenVINO.PaddleOCR.Models.Online" Version="0.8.1" />
    <PackageReference Include="Sdcb.OpenVINO.runtime.win-x64" Version="2026.2.0" />
    <PackageReference Include="SoundFlow" Version="1.4.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.2" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="EasyChat.Infrastructure.Windows.Tests" />
  </ItemGroup>
</Project>
